import './globals.css';
import Link from "next/link";
import { Metadata } from 'next';
import { Control } from './Control';

export const metadata: Metadata = {
  title: "Next.js practice App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const resp = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`, { cache: 'no-store' });
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/" className='font-bold text-5xl text-slate-500'>WEB</Link></h1>
        <ol>
          {topics.map((topic: any) => {
            return <li key={topic.id} className='font-normal text-indigo-700 text-blue underline'><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })
          }
        </ol>
        {children}
        <Control/>
      </body>
    </html>
  );
}
